/* This file was generated by SableCC (http://www.sablecc.org/). */

package parser;

import node.*;
import analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTDocStart(@SuppressWarnings("unused") TDocStart node)
    {
        this.index = 0;
    }

    @Override
    public void caseTDocEnd(@SuppressWarnings("unused") TDocEnd node)
    {
        this.index = 1;
    }

    @Override
    public void caseTDescr(@SuppressWarnings("unused") TDescr node)
    {
        this.index = 2;
    }

    @Override
    public void caseTDate(@SuppressWarnings("unused") TDate node)
    {
        this.index = 3;
    }

    @Override
    public void caseTAuthor(@SuppressWarnings("unused") TAuthor node)
    {
        this.index = 4;
    }

    @Override
    public void caseTAtdoc(@SuppressWarnings("unused") TAtdoc node)
    {
        this.index = 5;
    }

    @Override
    public void caseTString(@SuppressWarnings("unused") TString node)
    {
        this.index = 6;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 7;
    }
}
