/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import java.util.*;
import analysis.*;

@SuppressWarnings("nls")
public final class ADescrAst extends PAst
{
    private final LinkedList<TString> _string_ = new LinkedList<TString>();

    public ADescrAst()
    {
        // Constructor
    }

    public ADescrAst(
        @SuppressWarnings("hiding") List<?> _string_)
    {
        // Constructor
        setString(_string_);

    }

    @Override
    public Object clone()
    {
        return new ADescrAst(
            cloneList(this._string_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADescrAst(this);
    }

    public LinkedList<TString> getString()
    {
        return this._string_;
    }

    public void setString(List<?> list)
    {
        for(TString e : this._string_)
        {
            e.parent(null);
        }
        this._string_.clear();

        for(Object obj_e : list)
        {
            TString e = (TString) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._string_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._string_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._string_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<TString> i = this._string_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((TString) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
