/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AStringEAst extends PAst
{
    private TDocAt _docAt_;

    public AStringEAst()
    {
        // Constructor
    }

    public AStringEAst(
        @SuppressWarnings("hiding") TDocAt _docAt_)
    {
        // Constructor
        setDocAt(_docAt_);

    }

    @Override
    public Object clone()
    {
        return new AStringEAst(
            cloneNode(this._docAt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStringEAst(this);
    }

    public TDocAt getDocAt()
    {
        return this._docAt_;
    }

    public void setDocAt(TDocAt node)
    {
        if(this._docAt_ != null)
        {
            this._docAt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._docAt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._docAt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._docAt_ == child)
        {
            this._docAt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._docAt_ == oldChild)
        {
            setDocAt((TDocAt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
