/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AStringBAst extends PAst
{
    private TStringDocStar _stringDocStar_;

    public AStringBAst()
    {
        // Constructor
    }

    public AStringBAst(
        @SuppressWarnings("hiding") TStringDocStar _stringDocStar_)
    {
        // Constructor
        setStringDocStar(_stringDocStar_);

    }

    @Override
    public Object clone()
    {
        return new AStringBAst(
            cloneNode(this._stringDocStar_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStringBAst(this);
    }

    public TStringDocStar getStringDocStar()
    {
        return this._stringDocStar_;
    }

    public void setStringDocStar(TStringDocStar node)
    {
        if(this._stringDocStar_ != null)
        {
            this._stringDocStar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._stringDocStar_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._stringDocStar_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._stringDocStar_ == child)
        {
            this._stringDocStar_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._stringDocStar_ == oldChild)
        {
            setStringDocStar((TStringDocStar) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
