/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AStringGAst extends PAst
{
    private TSingleDocMail _singleDocMail_;

    public AStringGAst()
    {
        // Constructor
    }

    public AStringGAst(
        @SuppressWarnings("hiding") TSingleDocMail _singleDocMail_)
    {
        // Constructor
        setSingleDocMail(_singleDocMail_);

    }

    @Override
    public Object clone()
    {
        return new AStringGAst(
            cloneNode(this._singleDocMail_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStringGAst(this);
    }

    public TSingleDocMail getSingleDocMail()
    {
        return this._singleDocMail_;
    }

    public void setSingleDocMail(TSingleDocMail node)
    {
        if(this._singleDocMail_ != null)
        {
            this._singleDocMail_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._singleDocMail_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._singleDocMail_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._singleDocMail_ == child)
        {
            this._singleDocMail_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._singleDocMail_ == oldChild)
        {
            setSingleDocMail((TSingleDocMail) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
