/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AStringDAst extends PAst
{
    private TDocMail _docMail_;

    public AStringDAst()
    {
        // Constructor
    }

    public AStringDAst(
        @SuppressWarnings("hiding") TDocMail _docMail_)
    {
        // Constructor
        setDocMail(_docMail_);

    }

    @Override
    public Object clone()
    {
        return new AStringDAst(
            cloneNode(this._docMail_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStringDAst(this);
    }

    public TDocMail getDocMail()
    {
        return this._docMail_;
    }

    public void setDocMail(TDocMail node)
    {
        if(this._docMail_ != null)
        {
            this._docMail_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._docMail_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._docMail_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._docMail_ == child)
        {
            this._docMail_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._docMail_ == oldChild)
        {
            setDocMail((TDocMail) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
