/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AStringCAst extends PAst
{
    private TStringStarString _stringStarString_;

    public AStringCAst()
    {
        // Constructor
    }

    public AStringCAst(
        @SuppressWarnings("hiding") TStringStarString _stringStarString_)
    {
        // Constructor
        setStringStarString(_stringStarString_);

    }

    @Override
    public Object clone()
    {
        return new AStringCAst(
            cloneNode(this._stringStarString_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStringCAst(this);
    }

    public TStringStarString getStringStarString()
    {
        return this._stringStarString_;
    }

    public void setStringStarString(TStringStarString node)
    {
        if(this._stringStarString_ != null)
        {
            this._stringStarString_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._stringStarString_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._stringStarString_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._stringStarString_ == child)
        {
            this._stringStarString_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._stringStarString_ == oldChild)
        {
            setStringStarString((TStringStarString) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
