/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import java.util.*;
import analysis.*;

@SuppressWarnings("nls")
public final class AUserAst extends PAst
{
    private PAst _user_;
    private final LinkedList<PAst> _entries_ = new LinkedList<PAst>();

    public AUserAst()
    {
        // Constructor
    }

    public AUserAst(
        @SuppressWarnings("hiding") PAst _user_,
        @SuppressWarnings("hiding") List<?> _entries_)
    {
        // Constructor
        setUser(_user_);

        setEntries(_entries_);

    }

    @Override
    public Object clone()
    {
        return new AUserAst(
            cloneNode(this._user_),
            cloneList(this._entries_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAUserAst(this);
    }

    public PAst getUser()
    {
        return this._user_;
    }

    public void setUser(PAst node)
    {
        if(this._user_ != null)
        {
            this._user_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._user_ = node;
    }

    public LinkedList<PAst> getEntries()
    {
        return this._entries_;
    }

    public void setEntries(List<?> list)
    {
        for(PAst e : this._entries_)
        {
            e.parent(null);
        }
        this._entries_.clear();

        for(Object obj_e : list)
        {
            PAst e = (PAst) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._entries_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._user_)
            + toString(this._entries_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._user_ == child)
        {
            this._user_ = null;
            return;
        }

        if(this._entries_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._user_ == oldChild)
        {
            setUser((PAst) newChild);
            return;
        }

        for(ListIterator<PAst> i = this._entries_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAst) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
