/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TProgrammDoubleStringEnd extends Token
{
    public TProgrammDoubleStringEnd()
    {
        super.setText("\"");
    }

    public TProgrammDoubleStringEnd(int line, int pos)
    {
        super.setText("\"");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TProgrammDoubleStringEnd(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTProgrammDoubleStringEnd(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TProgrammDoubleStringEnd text.");
    }
}
