/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TProgrammDoubleTicks extends Token
{
    public TProgrammDoubleTicks()
    {
        super.setText("\"");
    }

    public TProgrammDoubleTicks(int line, int pos)
    {
        super.setText("\"");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TProgrammDoubleTicks(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTProgrammDoubleTicks(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TProgrammDoubleTicks text.");
    }
}
