/* This file was generated by SableCC (http://www.sablecc.org/). */

package analysis;

import node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseAStartAst(AStartAst node);
    void caseADocAst(ADocAst node);
    void caseAEntriesAst(AEntriesAst node);
    void caseAAuthorAst(AAuthorAst node);
    void caseADateAst(ADateAst node);
    void caseADescrAst(ADescrAst node);
    void caseAAtDocAst(AAtDocAst node);
    void caseAStringAAst(AStringAAst node);
    void caseAStringBAst(AStringBAst node);
    void caseAStringCAst(AStringCAst node);

    void caseTDocDescr(TDocDescr node);
    void caseTDocDate(TDocDate node);
    void caseTDocAuthor(TDocAuthor node);
    void caseTDocAtdoc(TDocAtdoc node);
    void caseTDocIdentifier(TDocIdentifier node);
    void caseTStringDocString(TStringDocString node);
    void caseTStringDocStar(TStringDocStar node);
    void caseTStringStarString(TStringStarString node);
    void caseTStringStarStar(TStringStarStar node);
    void caseTDocEnd(TDocEnd node);
    void caseTProgrammNoSlash(TProgrammNoSlash node);
    void caseTProrgrammSlash(TProrgrammSlash node);
    void caseTProgrammSingleTicks(TProgrammSingleTicks node);
    void caseTProgrammDoubleTicks(TProgrammDoubleTicks node);
    void caseTProgrammSlashSlash(TProgrammSlashSlash node);
    void caseTProgrammToStar(TProgrammToStar node);
    void caseTProgrammSlashAny(TProgrammSlashAny node);
    void caseTProgrammStarAny(TProgrammStarAny node);
    void caseTDocStart(TDocStart node);
    void caseTProgrammSingleString(TProgrammSingleString node);
    void caseTProgrammSingleStringEnd(TProgrammSingleStringEnd node);
    void caseTProgrammDoubleString(TProgrammDoubleString node);
    void caseTProgrammDoubleStringEnd(TProgrammDoubleStringEnd node);
    void caseEOF(EOF node);
}
