/* This file was generated by SableCC (http://www.sablecc.org/). */

package analysis;

import java.util.*;
import node.*;

public class AnalysisAdapter implements Analysis
{
    private Hashtable<Node,Object> in;
    private Hashtable<Node,Object> out;

    @Override
    public Object getIn(Node node)
    {
        if(this.in == null)
        {
            return null;
        }

        return this.in.get(node);
    }

    @Override
    public void setIn(Node node, Object o)
    {
        if(this.in == null)
        {
            this.in = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.in.put(node, o);
        }
        else
        {
            this.in.remove(node);
        }
    }

    @Override
    public Object getOut(Node node)
    {
        if(this.out == null)
        {
            return null;
        }

        return this.out.get(node);
    }

    @Override
    public void setOut(Node node, Object o)
    {
        if(this.out == null)
        {
            this.out = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.out.put(node, o);
        }
        else
        {
            this.out.remove(node);
        }
    }

    @Override
    public void caseStart(Start node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAStartSingleAst(AStartSingleAst node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAStartAst(AStartAst node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADocAst(ADocAst node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDocStart(TDocStart node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDocEnd(TDocEnd node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDescr(TDescr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDate(TDate node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAuthor(TAuthor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAtdoc(TAtdoc node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTString(TString node)
    {
        defaultCase(node);
    }

    @Override
    public void caseEOF(EOF node)
    {
        defaultCase(node);
    }

    public void defaultCase(@SuppressWarnings("unused") Node node)
    {
        // do nothing
    }
}
