/* This file was generated by SableCC (http://www.sablecc.org/). */

package analysis;

import java.util.*;
import node.*;

public class DepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    public void defaultOut(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getPAst().apply(this);
        node.getEOF().apply(this);
        outStart(node);
    }

    public void inAStartAst(AStartAst node)
    {
        defaultIn(node);
    }

    public void outAStartAst(AStartAst node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAStartAst(AStartAst node)
    {
        inAStartAst(node);
        {
            List<PAst> copy = new ArrayList<PAst>(node.getAst());
            for(PAst e : copy)
            {
                e.apply(this);
            }
        }
        outAStartAst(node);
    }

    public void inADocAst(ADocAst node)
    {
        defaultIn(node);
    }

    public void outADocAst(ADocAst node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADocAst(ADocAst node)
    {
        inADocAst(node);
        if(node.getAst() != null)
        {
            node.getAst().apply(this);
        }
        outADocAst(node);
    }

    public void inAEntriesAst(AEntriesAst node)
    {
        defaultIn(node);
    }

    public void outAEntriesAst(AEntriesAst node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEntriesAst(AEntriesAst node)
    {
        inAEntriesAst(node);
        {
            List<PAst> copy = new ArrayList<PAst>(node.getAst());
            for(PAst e : copy)
            {
                e.apply(this);
            }
        }
        outAEntriesAst(node);
    }

    public void inAAuthorAst(AAuthorAst node)
    {
        defaultIn(node);
    }

    public void outAAuthorAst(AAuthorAst node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAuthorAst(AAuthorAst node)
    {
        inAAuthorAst(node);
        if(node.getString() != null)
        {
            node.getString().apply(this);
        }
        outAAuthorAst(node);
    }

    public void inADateAst(ADateAst node)
    {
        defaultIn(node);
    }

    public void outADateAst(ADateAst node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADateAst(ADateAst node)
    {
        inADateAst(node);
        if(node.getString() != null)
        {
            node.getString().apply(this);
        }
        outADateAst(node);
    }

    public void inADescrAst(ADescrAst node)
    {
        defaultIn(node);
    }

    public void outADescrAst(ADescrAst node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADescrAst(ADescrAst node)
    {
        inADescrAst(node);
        {
            List<TString> copy = new ArrayList<TString>(node.getString());
            for(TString e : copy)
            {
                e.apply(this);
            }
        }
        outADescrAst(node);
    }

    public void inAAtDocAst(AAtDocAst node)
    {
        defaultIn(node);
    }

    public void outAAtDocAst(AAtDocAst node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAtDocAst(AAtDocAst node)
    {
        inAAtDocAst(node);
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        {
            List<TString> copy = new ArrayList<TString>(node.getDescription());
            for(TString e : copy)
            {
                e.apply(this);
            }
        }
        outAAtDocAst(node);
    }
}
